name: Auto Scraper

on:
  schedule:
    - cron: "0 2 * * 0"  # Every Sunday at 2 AM UTC
  workflow_dispatch:     # Manual trigger option (for demo)

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Microsoft Edge
        run: |
          sudo apt-get update
          sudo apt-get install -y microsoft-edge-stable
  
      - name: Install Edge Driver
        run: |
          EDGEDRIVER_VERSION=$(curl -sS https://msedgedriver.azureedge.net/LATEST_RELEASE_STABLE)
          wget "https://msedgedriver.azureedge.net/${EDGEDRIVER_VERSION}/edgedriver_linux64.zip"
          unzip edgedriver_linux64.zip
          sudo mv msedgedriver /usr/local/bin/

      - name: Install Pythondependencies
        run: pip install -r requirements.txt

      - name: Run all scrapers
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          python daraz_scraper.py
        #   python khadii_scraper.py
        #   python review_scraper.py
        #   python sapphire_scraper.py
        #   python description_generator.py